import Alert from '../../alert';
import { initDatepicker } from '../../components/datepicker';
import { initializeEstimatedTimeInputs } from '../../components/estimated-time-input';
import { initTomSelect } from '../../components/tom-select';

const ADVANCED_FIELDS = new Set(['description', 'task_type_id', 'task_mode_id', 'priority', 'is_billable']);
const scheduleTaskEditors = new WeakMap();

/**
 * Calculate the last day of the month for a given date string (YYYY-MM-DD format)
 * @param {string} dateString - Date string in YYYY-MM-DD format
 * @returns {string} Last day of the month in YYYY-MM-DD format
 */
const getLastDayOfMonth = (dateString) => {
    if (!dateString) return '';
    const [year, month] = dateString.split('-').slice(0, 2);
    const lastDay = new Date(year, month, 0).getDate();
    return `${year}-${month}-${String(lastDay).padStart(2, '0')}`;
};

/**
 * Update the End Date based on the Start Date
 * Only auto-updates if: creating new schedule, end date is empty, or end date equals previously auto-generated value
 * @param {HTMLFormElement} form - The schedule task form
 * @param {boolean} forceUpdate - Force update regardless of current end date value
 */
const updateEndDateFromStartDate = (form, forceUpdate = false) => {
    const startDateField = form.querySelector('[data-schedule-date="start"]');
    const endDateField = form.querySelector('[data-schedule-date="end"]');

    if (!startDateField || !endDateField) return;

    const startDateValue = startDateField.value;
    if (!startDateValue) return;

    const endDateValue = endDateField.value;
    const wasAutoGenerated = endDateField.dataset.scheduleEndDateGenerated === 'true';
    const isEndDateEmpty = !endDateValue;

    // Only update if: forcing update, end date is empty, or it was previously auto-generated
    if (!forceUpdate && !isEndDateEmpty && !wasAutoGenerated) {
        return;
    }

    const lastDay = getLastDayOfMonth(startDateValue);
    if (lastDay) {
        if (endDateField._flatpickr) {
            endDateField._flatpickr.setDate(lastDay, true, 'Y-m-d');
        } else {
            endDateField.value = lastDay;
        }
        endDateField.dataset.scheduleEndDateGenerated = 'true';
    }
};

const parseJson = (node, fallback = {}) => {
    try {
        return JSON.parse(node?.textContent || '{}');
    } catch (error) {
        return fallback;
    }
};

const dependencies = parseJson(document.getElementById('schedule-task-dependencies'), { projects: {} });

const FREQUENCY_NOTES = {
    daily: "A task will be generated every working day based on the assigned user's active shift. No task will be generated on shift week-off days or when no valid shift assignment exists.",
    weekdays: 'A task will be generated only on the selected weekdays within the configured date range.',
    weekly: 'A task will be generated once every week on the selected weekday within the configured date range.',
    monthly: 'A task will be generated on the selected day(s) of each month within the configured date range.',
};

const setSelectOptions = (field, options, placeholder, value = '') => {
    if (!field) return;

    const normalizedValue = String(value || '');

    if (field.tomselect) {
        field.tomselect.clear(true);
        field.tomselect.clearOptions();
        field.tomselect.settings.placeholder = placeholder;
        field.tomselect.addOption(options);
        field.tomselect.refreshOptions(false);
        field.tomselect.setValue(normalizedValue, true);
        field.tomselect.inputState();
        return;
    }

    field.innerHTML = `<option value="">${placeholder}</option>`;
    options.forEach((option) => {
        const element = document.createElement('option');
        element.value = option.value;
        element.textContent = option.text;
        field.appendChild(element);
    });
    field.value = normalizedValue;
};

const setDuration = (form, name, minutes) => {
    const field = form.querySelector(`[name="${name}"]`);
    if (!field) return;

    field.value = String(Math.max(0, Number.parseInt(minutes || '0', 10) || 0));
    field.closest('[data-estimated-time]')?.dispatchEvent(new Event('estimated-time:refresh'));
};

const syncProjectFields = (form, initial = {}, useProjectDefaults = false) => {
    const projectId = String(form.querySelector('[name="project_id"]')?.value || '');
    const project = dependencies.projects?.[projectId];
    const milestoneValue = String(initial.project_milestone_id || '');
    const sprintValue = String(initial.project_sprint_id || '');
    const assigneeValue = String(initial.current_assignee_id || '');

    setSelectOptions(
        form.querySelector('[name="project_milestone_id"]'),
        project?.milestones || [],
        project ? 'Select milestone' : 'Select project first',
        milestoneValue
    );

    const sprints = (project?.sprints || []).filter((sprint) => (
        !milestoneValue || String(sprint.project_milestone_id || '') === milestoneValue
    ));
    setSelectOptions(
        form.querySelector('[name="project_sprint_id"]'),
        sprints,
        project ? 'Select sprint' : 'Select project first',
        sprintValue
    );
    setSelectOptions(
        form.querySelector('[name="current_assignee_id"]'),
        project?.assignees || [],
        project ? 'Select assignee' : 'Select project first',
        assigneeValue
    );

    if (useProjectDefaults && project) {
        setDuration(form, 'estimated_time_minutes', project.default_task_estimate_minutes || 0);
        const billable = form.querySelector('[name="is_billable"][type="checkbox"]');
        if (billable) billable.checked = Boolean(project.default_billable);
    }
};

const syncSprintFields = (form) => {
    const projectId = String(form.querySelector('[name="project_id"]')?.value || '');
    const milestoneId = String(form.querySelector('[name="project_milestone_id"]')?.value || '');
    const project = dependencies.projects?.[projectId];
    const sprintField = form.querySelector('[name="project_sprint_id"]');
    const currentSprint = String(sprintField?.value || '');
    const sprints = (project?.sprints || []).filter((sprint) => (
        !milestoneId || String(sprint.project_milestone_id || '') === milestoneId
    ));

    setSelectOptions(
        sprintField,
        sprints,
        project ? 'Select sprint' : 'Select project first',
        sprints.some((sprint) => String(sprint.value) === currentSprint) ? currentSprint : ''
    );
};

const syncFrequencyNote = (form, frequency) => {
    const note = form.querySelector('[data-schedule-frequency-note]');
    if (!note) return;

    note.textContent = FREQUENCY_NOTES[frequency] || FREQUENCY_NOTES.daily;
};

const syncFrequency = (form) => {
    const frequency = form.querySelector('[name="frequency_type"]')?.value || 'daily';
    form.querySelectorAll('[data-schedule-frequency-section]').forEach((section) => {
        section.hidden = section.dataset.scheduleFrequencySection !== frequency;
    });
    syncFrequencyNote(form, frequency);
};

const initializeScheduleDates = (modal) => {
    modal.querySelectorAll('[data-schedule-date]').forEach((field) => {
        const initialDate = field.value || null;
        const selector = `[data-schedule-date="${field.dataset.scheduleDate}"]`;

        initDatepicker(selector, {
            defaultDate: initialDate,
            onChange: (selectedDates, dateString, instance) => {
                instance.input.value = selectedDates.length ? dateString : '';
            },
        }, modal);
    });
};

const syncScheduleDateValues = (form) => {
    form.querySelectorAll('[data-schedule-date]').forEach((field) => {
        const picker = field._flatpickr;

        if (!picker) return;

        field.value = picker.selectedDates.length
            ? picker.formatDate(picker.selectedDates[0], 'Y-m-d')
            : '';
    });
};

const clearErrors = (form) => {
    form.querySelectorAll('[data-schedule-task-error]').forEach((node) => {
        node.textContent = '';
        node.classList.add('hidden');
    });
    form.querySelectorAll('.border-red-500').forEach((node) => node.classList.remove('border-red-500'));
};

const showErrors = (form, errors) => {
    clearErrors(form);

    Object.entries(errors).forEach(([name, messages]) => {
        const baseName = name.split('.')[0];
        const field = form.querySelector(`[name="${baseName}"], [name="${baseName}[]"]`);
        const error = form.querySelector(`[data-schedule-task-error="${baseName}"]`);
        (field?.tomselect?.control || field)?.classList.add('border-red-500');

        if (error) {
            error.textContent = Array.isArray(messages) ? messages[0] : String(messages || '');
            error.classList.remove('hidden');
        }
    });

    if (Object.keys(errors).some((name) => ADVANCED_FIELDS.has(name.split('.')[0]))) {
        form.querySelector('[data-schedule-task-advanced]')?.removeAttribute('hidden');
        const toggle = form.querySelector('[data-schedule-advanced-toggle]');
        if (toggle) toggle.textContent = 'Hide Advanced';
    }
};

const prepareModal = (modal) => {
    const form = modal?.querySelector('[data-schedule-task-form]');
    if (!form) return;

    initTomSelect(modal);
    initializeEstimatedTimeInputs(form);
    initializeScheduleDates(modal);

    const initial = parseJson(modal.querySelector('[data-schedule-task-initial]'), {});
    syncProjectFields(form, initial);
    setDuration(form, 'estimated_time_minutes', initial.estimated_time_minutes ?? form.querySelector('[name="estimated_time_minutes"]')?.value);

    const dueAfterField = form.querySelector('[name="due_after_seconds"]');
    const initialDueAfterMinutes = initial.due_after_seconds !== undefined
        ? Math.floor(initial.due_after_seconds / 60)
        : dueAfterField?.value;
    setDuration(form, 'due_after_seconds', initialDueAfterMinutes);

    syncFrequency(form);

    // Detect if end date was auto-generated (when editing)
    const startDateField = form.querySelector('[data-schedule-date="start"]');
    const endDateField = form.querySelector('[data-schedule-date="end"]');
    if (startDateField && endDateField && startDateField.value && endDateField.value) {
        const calculatedLastDay = getLastDayOfMonth(startDateField.value);
        if (calculatedLastDay === endDateField.value) {
            endDateField.dataset.scheduleEndDateGenerated = 'true';
        }
    }

    const editorElement = modal.querySelector('#schedule_task_description_editor');
    if (editorElement && !scheduleTaskEditors.has(modal)) {
        const descInput = modal.querySelector('#schedule_task_description_input');
        const initialValue = descInput ? descInput.value : '';

        const quill = new window.Quill(editorElement, {
            theme: 'snow',
            placeholder: 'Enter schedule description...',
        });

        if (initialValue) {
            quill.clipboard.dangerouslyPasteHTML(initialValue);
        }

        scheduleTaskEditors.set(modal, quill);
    }
};

const resetCreateModal = (modal) => {
    const form = modal?.querySelector('[data-schedule-task-form]');
    if (!form || modal.dataset.scheduleTaskModal !== 'create') return;

    form.reset();
    clearErrors(form);

    const editor = scheduleTaskEditors.get(modal);
    if (editor) {
        editor.setContents([]);
    }
    const descInput = modal.querySelector('#schedule_task_description_input');
    if (descInput) {
        descInput.value = '';
    }

    form.querySelectorAll('select').forEach((field) => {
        if (field.tomselect) {
            field.tomselect.setValue(field.value || '', true);
        }
    });

    syncProjectFields(form, {});
    setDuration(form, 'estimated_time_minutes', 0);
    setDuration(form, 'due_after_seconds', 0);

    const advancedSection = form.querySelector('[data-schedule-task-advanced]');
    const advancedToggle = form.querySelector('[data-schedule-advanced-toggle]');
    if (advancedSection) advancedSection.hidden = true;
    if (advancedToggle) advancedToggle.textContent = 'Show Advanced';

    const frequencyField = form.querySelector('[name="frequency_type"]');
    if (frequencyField?.tomselect) {
        frequencyField.tomselect.setValue('daily', true);
    } else if (frequencyField) {
        frequencyField.value = 'daily';
    }
    syncFrequency(form);

    const today = modal.dataset.today;
    const startDate = form.querySelector('[data-schedule-date="start"]');
    const endDate = form.querySelector('[data-schedule-date="end"]');

    startDate?._flatpickr?.setDate(today, true, 'Y-m-d');

    // Clear end date and set auto-generated flag to false for new schedules
    if (endDate?._flatpickr) {
        endDate._flatpickr.clear();
    } else {
        endDate.value = '';
    }
    endDate.dataset.scheduleEndDateGenerated = 'false';

    // Auto-populate end date based on start date
    updateEndDateFromStartDate(form, true);
};

const openModal = (modal) => {
    prepareModal(modal);
    modal?.classList.remove('hidden');
    modal?.classList.add('flex');
};

const closeModal = (modal) => {
    modal?.classList.add('hidden');
    modal?.classList.remove('flex');
};

const requestJson = async (url, options = {}) => {
    const response = await fetch(url, {
        ...options,
        headers: {
            Accept: 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content || '',
            ...(options.headers || {}),
        },
    });
    const result = await response.json();
    return { response, result };
};

const initializeScheduleTasks = () => {
    const page = document.querySelector('[data-schedule-task-page]');
    if (!page) return;

    const createModal = page.querySelector('[data-schedule-task-modal="create"]');
    if (createModal) prepareModal(createModal);

    page.addEventListener('click', async (event) => {
        const openButton = event.target.closest('[data-schedule-task-open]');
        if (openButton) {
            const editHost = page.querySelector('[data-schedule-task-edit-host]');
            if (editHost) editHost.innerHTML = '';

            const freshCreateModal = page.querySelector('[data-schedule-task-modal="create"]');
            prepareModal(freshCreateModal);
            resetCreateModal(freshCreateModal);
            openModal(freshCreateModal);
            return;
        }

        const closeButton = event.target.closest('[data-schedule-task-close]');
        if (closeButton) {
            closeModal(closeButton.closest('[data-schedule-task-modal]'));
            return;
        }

        const advancedButton = event.target.closest('[data-schedule-advanced-toggle]');
        if (advancedButton) {
            const section = advancedButton.closest('form')?.querySelector('[data-schedule-task-advanced]');
            if (section) {
                section.hidden = !section.hidden;
                advancedButton.textContent = section.hidden ? 'Show Advanced' : 'Hide Advanced';
            }
            return;
        }

        const editButton = event.target.closest('[data-schedule-task-edit]');
        if (editButton) {
            editButton.disabled = true;
            try {
                const { response, result } = await requestJson(editButton.dataset.url);
                if (!response.ok || !result.status) throw new Error(result.message || 'Unable to load the schedule.');

                const host = page.querySelector('[data-schedule-task-edit-host]');
                host.innerHTML = result.html;
                openModal(host.querySelector('[data-schedule-task-modal="edit"]'));
            } catch (error) {
                Alert.errorModal(error.message || 'Unable to load the schedule.');
            } finally {
                editButton.disabled = false;
            }
            return;
        }

        const toggleButton = event.target.closest('[data-schedule-task-toggle]');
        if (toggleButton) {
            const active = toggleButton.dataset.active === 'true';
            const action = active ? 'disable' : 'enable';
            const confirmation = await Alert.confirm({
                title: `${active ? 'Disable' : 'Enable'} scheduled task?`,
                text: `This will ${action} future runs of this schedule.`,
                confirmText: `Yes, ${action}`,
            });
            if (!confirmation.isConfirmed) return;

            try {
                const { response, result } = await requestJson(toggleButton.dataset.url, { method: 'PATCH' });
                if (!response.ok || !result.success) throw new Error(result.message || 'Unable to update the schedule.');
                window.location.reload();
            } catch (error) {
                Alert.errorModal(error.message || 'Unable to update the schedule.');
            }
            return;
        }

        const deleteButton = event.target.closest('[data-schedule-task-delete]');
        if (deleteButton) {
            const confirmation = await Alert.confirm({
                title: 'Are you sure you want to delete this Schedule Task?',
                text: 'Future tasks will no longer be generated. Existing generated tasks will remain unchanged.',
                confirmText: 'Yes, delete',
                confirmColor: '#ef4444',
            });
            if (!confirmation.isConfirmed) return;

            try {
                const { response, result } = await requestJson(deleteButton.dataset.url, { method: 'DELETE' });
                if (!response.ok || !result.status) throw new Error(result.message || 'Unable to delete the schedule.');
                window.location.reload();
            } catch (error) {
                Alert.errorModal(error.message || 'Unable to delete the schedule.');
            }
        }
    });

    page.addEventListener('change', (event) => {
        const form = event.target.closest('[data-schedule-task-form]');
        if (!form) return;

        if (event.target.matches('[name="project_id"]')) {
            syncProjectFields(form, {}, true);
        } else if (event.target.matches('[name="project_milestone_id"]')) {
            syncSprintFields(form);
        } else if (event.target.matches('[name="frequency_type"]')) {
            syncFrequency(form);
        } else if (event.target.matches('[data-schedule-date="start"]')) {
            // Auto-update end date when start date changes
            updateEndDateFromStartDate(form);
        } else if (event.target.matches('[data-schedule-date="end"]')) {
            // Mark end date as manually selected when user changes it
            if (event.target.value) {
                event.target.dataset.scheduleEndDateGenerated = 'false';
            }
        }
    });

    page.addEventListener('submit', async (event) => {
        const form = event.target.closest('[data-schedule-task-form]');
        if (!form) return;
        event.preventDefault();
        clearErrors(form);
        syncScheduleDateValues(form);

        const editor = scheduleTaskEditors.get(form.closest('[data-schedule-task-modal]'));
        if (editor) {
            const descInput = form.querySelector('#schedule_task_description_input');
            if (descInput) {
                const html = editor.root.innerHTML;
                descInput.value = (html === '<p><br></p>' || html === '<p></p>') ? '' : html;
            }
        }

        const submit = form.querySelector('[data-schedule-task-submit]');
        const originalText = submit?.textContent;
        if (submit) {
            submit.disabled = true;
            submit.textContent = 'Saving...';
        }

        const formData = new FormData(form);
        const dueAfterField = form.querySelector('[name="due_after_seconds"]');
        if (dueAfterField && dueAfterField.value) {
            formData.set('due_after_seconds', String(Number(dueAfterField.value) * 60));
        }

        try {
            const { response, result } = await requestJson(form.dataset.url, {
                method: 'POST',
                body: formData,
            });
            if (response.status === 422 && result.errors) {
                showErrors(form, result.errors);
                return;
            }
            if (!response.ok || !result.status) throw new Error(result.message || 'Unable to save the schedule.');
            window.location.reload();
        } catch (error) {
            Alert.errorModal(error.message || 'Unable to save the schedule.');
        } finally {
            if (submit) {
                submit.disabled = false;
                submit.textContent = originalText;
            }
        }
    });
};

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initializeScheduleTasks);
} else {
    initializeScheduleTasks();
}
